name: $(Date:yyyyMMdd)$(Rev:.r)
parameters:
  - name: vmImages
    displayName: VM Images
    type: object
    default: ["ubuntu-latest"]
  - name: pythonVersions
    displayName: Python Versions
    type: object
    default: ["3.7", "3.8", "3.9"]
jobs:
  ${{ vmImage in parameters.vmImages }}:
    - job: Testing_${{ replace(vmImage, '-', '') }}
      displayName: Testing - ${{ vmImage }} -
      pool:
        vmImage: ${{ vmImage }}
      strategy:
        matrix:
          ${{ each pythonVersion in parameters.pythonVersions }}:
            "Python${{ pythonVersion }}":
              pythonVersion: '${{ pythonVersion }}'
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '$(pythonVersion)'
